const fs = require('fs');
const path = require('path');

// List of 220 dealer codes provided by the user
const DEALER_CODES = [
  "FAUA", "JADB", "TBN", "JIMF", "OTM", "KCCD", "SAJU", "EGMT", "GEE", "HAGA",
  "KCBW", "JIMG", "FFQA", "NAVB", "HIJKB", "LLA", "BJTABB", "YAIZ", "SAJV", "LCHC",
  "PDAC", "TEJ", "EAQ", "RAUA", "KCBX", "THFW", "THFX", "EGKHSH", "TAQBB", "HBR",
  "YAEF", "SHJ", "PDAQ", "DABC", "TDI", "YAIE", "JADC", "EDIA", "RJHB", "HHY",
  "DAAE", "TEEOT", "DAAK", "TEN", "TDGB", "PBA", "LEM", "OBR", "TEEOW", "TEEOG",
  "GCGB", "SBM", "TAVA", "NDX", "HLBB", "JIHRB", "LECH", "JJF", "DABM", "TFKB",
  "EHRB", "EGKA", "WKQD", "THCAA", "YKA", "TEEOU", "RDS", "TABK", "GFH", "TDSE",
  "YACP", "KDY", "EGOC", "KCCI", "IAAE", "FAUPA", "YAIO", "HIJGB", "GAGB", "AYU",
  "EKM", "TFL", "JIHJB", "EGJC", "LCHAB", "YAEH", "TEEOF", "EGKO", "KDNA", "EGJB",
  "TJJ", "WKTA", "BJTB", "FDNB", "JIHWB", "GOPB", "KCEZ", "HHX", "EGIZ", "TACFB",
  "GOWB", "OQEBB", "ORGA", "YAJC", "HDAO", "KCEY", "YAEG", "THCQ", "JIMH", "YAJI",
  "HKTA", "OQEAB", "OQECB", "JIHMB", "JCMB", "GFWA", "HEAL", "TACM", "THGE", "SAADA",
  "SCYA", "RCDB", "HLCA", "HLD", "TEFJ", "TDSZA", "LECF", "TEEHB", "KCDT", "TACR",
  "AYUA", "TEEJA", "TEEO", "GEAU", "TBND", "HBIJ", "YAHN", "TEFB", "THFZ", "GEAA",
  "YAEI", "TEDU", "RDT", "NDNA", "TACZA", "NDLA", "HBIT", "DAAC", "HFXDA", "YAAPA",
  "LIEB", "BJTAEB", "YAEB", "THGG", "HBIQ", "OSB", "JJE", "EGJM", "THED", "JCRB",
  "KCEL", "YAAR", "EBAE", "OSY", "RCK", "YAHO", "HLDB", "LIG", "GOXB", "GABW",
  "THCL", "YAIP", "EBAL", "JJA", "FEK", "SAJW", "TEEPV", "BJTC", "KCCB", "LIN",
  "THCLA", "YAIQ", "EGPH", "YAIW", "YADT", "RCQ", "SAJR", "FEG", "TEEOS", "GEAV",
  "YADX", "YAIJ", "KGCA", "EGJA", "THCZ", "HDAI", "THCY", "WKTE", "EBAQ", "PBB",
  "TEDE", "RDU", "EGKC", "SAJZ", "TEDG", "LEBP", "IAAC", "LEBY", "TEDK", "RDB",
  "SHG", "OTP", "PGH", "VAAC", "MAAD", "FEAY", "DABA", "JJV", "DABD", "DABJ"
];

const DEALER_NAMES = [
  "LIMA MOTOR, PD", "SUMBER REJEKI, CV", "MURNI MOTOR I, PT", "BERDIKARI MOTOR JAYA, PT",
  "SINARMAS MOTOR, CV", "SINAR ABADI, PD", "SELAMAT LESTARI MANDIRI, PT", "ARTA CITRA HARMONI, PT",
  "FORTUNA MOTOR, CV", "MERDEKA MOTOR, PT", "SETIA KAWAN MOTOR I, PD", "BERDIKARI MOTOR JAYA II, PT",
  "MARCONI MANDIRIPERKASA, PT", "LIMA MOTOR, PD", "DAYA ANUGRAH MANDIRI, PT", "PRIMA KUNING KENCANA, PT",
  "DAYA ANUGRAH MANDIRI, PT", "MERDEKA MOTOR, PT", "SELAMAT LESTARI MANDIRI, PT", "MULIA MOTOR II, PD",
  "NETRAL JAYA MOTOR, PT", "MURNI PUTRAMAS, PT", "PERWIRATAMA DARMAGUNA, PT", "DUTA NIAGA MULTI SEJAHTERA, PT",
  "SETIA KAWAN MOTOR II, PD", "MURNI MOTOR II, PT", "MURNI MOTOR III, PT", "DAYA ADICIPTA MOTORA, PT",
  "DAYA ANUGRAH MANDIRI, PT", "GRAHA PRAWIRA DANISWARA, PT", "PACIFIC MOTOR I, PT", "TERUS JAYA SENTOSA MOTOR, PT",
  "SETIA KAWAN MOTOR III, PD", "WIJAYA ABADI, PD", "KUSUMASEJATI INTIPRIMA, PT", "VIRGI MOTOR, PD",
  "SUMBER REJEKI, CV", "SINAR REJEKI MOTOR, PT", "AMARTA SAYAP MERAH, PT", "RIFANA MULYA ABADI, CV",
  "SINAR KARYA MAKMUR, CV", "STAR MOTOR I, PD", "AMARTA SAYAP MERAH, PT", "PRABUPENDAWA MANUNGGAL, PT",
  "TRI KARYATAMA JAYA, PT", "SETIA KAWAN MOTOR I, PD", "KARYA PERDANA, CV", "SUBUR JAYA, CV",
  "STAR MOTOR II, PD", "PRAKASA II, PD", "NUSANTARA SURYA SAKTI, PT", "MEGA MOTOR, CV",
  "GUNA MOTOR, CV", "SURYA WIJAYA SEJAHTERA, CV", "DAYA ANUGRAH MANDIRI, PT", "DAYA ANUGRAH MANDIRI, PT",
  "DEASSY SUKSES MANDIRI, PT", "CEMARA AGUNG PERDANA, PT", "Berkat Abadi Motor, CV", "LESTARI MOTOR, CV",
  "HARI BARU GEMILANG, PT", "CEMARA AGUNG SEJAHTERA, PT", "ARTAMAS KURNIA, PT", "BINTANG NIAGA JAYA, PT",
  "MITRA JAYA, CV", "STAR MOTOR III, PD", "AGUNG MOTOR, CV", "MEGA MOTOR, CV",
  "LIMA MOTOR, PD", "PELANGI PRIMA MANDIRI, CV", "BINTANG ALAM JAYA, PT", "PERMATA DHARMA FORTUNA, CV",
  "WIJAYA ADIPURA SENTOSA, PT", "PRIMA DJAJA SADAYA, PT", "DWI SETIA KAWAN, PD", "LIMA MOTOR, PD",
  "MITRA JAYA, CV", "DAYA ANUGRAH MANDIRI, PT", "LIMA MOTOR, PD", "NAGAMAS MITRA ABADI, CV",
  "DAYA ALVITA MANDIRI, PT", "ANUGERAH SEJAHTERA, CV", "DAYA ANUGRAH MANDIRI, PT", "GELORA FAJAR PERKASA, PT",
  "MULIA MOTOR I, PD", "PACIFIC MOTOR III, PT", "PRAKASA I, PD", "REJEKI PUTERA MANDIRI, CV",
  "SEJAHTERA MULIA MOTOR, PD", "WAHANAARTHA RITELINDO, PT", "PUTERA MERDEKA, CV", "ASTRA INTERNATIONAL- HSO, PT",
  "DAYA ANUGRAH MANDIRI, PT", "DAYA ANUGRAH MANDIRI, PT", "DAYA ANUGRAH MANDIRI, PT", "DUTA VICTORY RAYA, CV",
  "PACIFIC AREA JAYA , PT", "CATUR PUTRA JAYA, PT", "NETRAL JAYA MOTOR, PT", "DAYA ANUGRAH MANDIRI, PT",
  "DAYA ANUGRAH MANDIRI, PT", "DAYA ANUGRAH MANDIRI, PT", "AGUNG JAYA BERSAMA, PT", "AMARTA SAYAP MERAH, PT",
  "BINTANG MOTOR JAYA, PT ", "MITRA UTAMA MOTORA, PT", "PACIFIC MOTOR II, PT", "SUPRA JAYA MOTOR, CV",
  "BERDIKARI MOTOR JAYA III, PT", "PACIFIC AREA JAYA , PT", "CAKRA LAKSANA SAKTI, PT", "DAYA ANUGRAH MANDIRI, PT",
  "DAYA ANUGRAH MANDIRI, PT", "DAYA ANUGRAH MANDIRI, PT", "DAYA ANUGRAH MANDIRI, PT", "DAYA ANUGRAH MANDIRI, PT",
  "DAYA ANUGRAH MANDIRI, PT", "SETIA ANUGERAH MOTOR, PT", "KUSUMASEJATI INTIPRIMA, PT", "DAYA ANUGRAH MANDIRI, PT",
  "NUSANTARA SURYA SAKTI, PT", "DAYA ANUGRAH MANDIRI, PT", "BINTANG KEMAKMURAN, PT", "TUNAS DWIPA MATRA, PT",
  "BINTANG MOTOR JAYA, PT", "RINA MITRA RAHARJA, PT", "TRIDJAYA ANUGERAH SUKSES, CV", "DAYA ANUGRAH MANDIRI, PT",
  "BINTANG ANUGRAH MOTOR, PT", "SOLUSI TULUS MITRA, PT", "NAGAMAS MITRA SENTOSA, CV", "DAYA ANUGRAH MANDIRI, PT",
  "METAGUNA INNOVA, PT", "CEMARA AGUNG PRATAMA, PT", "MURNI MOTOR IV, PT", "MURNI SUBAJA MAS, PT",
  "SUPRAJAYA MOTOR, CV", "BERKAH PRIMA SEJATI, PT", "KIRANA MOTORINDO JAYA, CV", "RAMA, CV",
  "PACIFIC MOTOR IV, PT", "CATUR PUTRA JAYA, PT", "AGUNG MOTOR, CV", "ANUGRAH HASTA MULIA, PT",
  "SANPRIMA SENTOSA, PT", "CEMARA GUNA LESTARI, CV", "CIBITUNG MOTOR MANDIRI, PT", "SETIA ABADI MITRA MOTOR, PT",
  "RODA MITRA LESTARI, CV", "KUJANG SAKTI ANUGRAH, PT", "DAYA ANUGRAH MANDIRI, PT", "DAYA ANUGRAH MANDIRI, PT",
  "BERKAH PRATAMA SINERGI, PT", "DESCONINDOTAMA, PT", "MILLENIUM PUTRA MOTOR, CV", "NETRAL JAYA MOTOR, PT",
  "SINAR MAKMUR, CV", "EKA SURYA WIJAYA, PT", "CATUR PUTRA JAYA, PT", "DAYA ANUGRAH MANDIRI, PT",
  "BINTANG MOTOR JAYA, PT", "SINAR MULIA SEJAHTERA, PT", "DWI PUTRA ANUGRAH PERKASA, PT", "NIAGA REDJA ABADI, PT",
  "RODA MAS AUTO LESTARI, CV", "SUPRA JAYA MOTOR, CV", "TUNAS DWIPA MATRA, PT", "AS PUTRA RAHMAT, CV",
  "DAYA ANUGRAH MANDIRI, PT", "PLATINUM MANDIRI SEJAHTERA, PT", "HARIKA PRIMA SAKTI, PT", "MITRA JAYA, CV",
  "NAGAMAS MITRA ABADI, CV", "NAFRIYA ABADI MOTOR, PT", "TRIDJAYA SEJAHTERA SUKSES, CV", "SELAMAT LESTARI MANDIRI, PT",
  "VIRGI MOTOR, PT", "DAYA ANUGRAH MANDIRI, PT", "AMARTA SAYAP MERAH, PT", "AMARTA SAYAP MERAH, PT",
  "HARIKA PRIMA SAKTI, PT", "BINTANG ALAM JAYA, PT", "MITRADEKA MANDIRI, PT", "CIBITUNG MOTOR MANDIRI, PT",
  "CATUR ANUGERAH MANDIRI, PT", "DAYA ANUGRAH MANDIRI, PT", "DAYA ANUGRAH MANDIRI, PT", "PACIFIC MOTOR, PT",
  "MARCONI MANDIRIPERKASA, PT", "CEMARA AGUNG PRATAMA, PD", "BEKASI MOTOR, PT", "METAGUNA INNOVA, PT",
  "MITRA UTAMA, PD", "WIJAYA ABADI MULIA, PT", "MITRA SEHATI JAYA, CV", "HARIKA PRIMA SAKTI, PT",
  "DHARMA MAKMUR BERSAMA, PT", "MITRA PINASTHIKA MUSTIKA, PT", "DAYA ANUGRAH MANDIRI, PT", "ASTRA INTERNATIONAL- HSO, PT",
  "DAYA ANUGRAH MANDIRI, PT", "SUPRA JAYA MOTOR, CV", "SEJAHTERA INTI ANUGRAH PERKASA, PT", "TUNAS DWIPA MATRA, PTgit",
  "TUNAS DWIPA MATRA, PT", "DAYA ANUGRAH MANDIRI, PT", "NAFRIYA ABADI MOTOR, PT", "MAWAR MOTOR FAYURI, PT",
  "BARENO TIGA BERSAUDARA, PT", "NUSANTARA SURYA SAKTI, PT", "ASTRA INTERNATIONAL, PT", "NATA DAYA MANDIRI, CV",
  "BUDIMAN MOTOR", "DAYA ANUGRAH MANDIRI, PT", "HELMI MOTOR", "PANDAWA MOTOR, PD",
  "DAYA ANUGRAH MANDIRI, PT", "WAHANAARTHA RITELINDO, PT", "TRIDJAYA MERDEKA SUKSES, PT", "BERUANG MOTOR TERPADU, CV"
];

const DEALER_AREAS = [
  "SUBANG", "SUMEDANG", "BOGOR", "MAJALENGKA", "TASIKMALAYA", "CIREBON", "SUKABUMI", "BANDUNG", "PURWAKARTA", "BEKASI",
  "CIREBON", "MAJALENGKA", "SUBANG", "GARUT", "BEKASI", "KUNINGAN", "BANDUNG", "BEKASI", "SUKABUMI", "INDRAMAYU",
  "CIAMIS", "DEPOK", "BANDUNG", "CIANJUR", "CIREBON", "BOGOR", "BOGOR", "BANDUNG", "DEPOK", "BEKASI",
  "BEKASI", "SUKABUMI", "CIAMIS", "BANDUNG", "BOGOR", "BEKASI", "SUMEDANG", "BANDUNG", "BANDUNG", "BEKASI",
  "BANDUNG", "KARAWANG", "BANDUNG", "DEPOK", "BOGOR", "CIAMIS", "INDRAMAYU", "TASIKMALAYA", "KARAWANG", "KARAWANG",
  "KARAWANG", "SUKABUMI", "BOGOR", "GARUT", "BEKASI", "CIREBON", "INDRAMAYU", "SUMEDANG", "BANDUNG", "BOGOR",
  "BANDUNG", "BANDUNG", "BEKASI", "BOGOR", "BEKASI", "KARAWANG", "CIANJUR", "BOGOR", "PURWAKARTA", "BOGOR",
  "BEKASI", "CIREBON", "BANDUNG", "CIREBON", "INDRAMAYU", "SUBANG", "DEPOK", "BEKASI", "KARAWANG", "BANDUNG",
  "BANDUNG", "BOGOR", "CIREBON", "BANDUNG", "INDRAMAYU", "BEKASI", "KARAWANG", "BANDUNG", "CIREBON", "BANDUNG",
  "BOGOR", "BANDUNG", "BANDUNG", "SUBANG", "INDRAMAYU", "KARAWANG", "CIREBON", "BEKASI", "BANDUNG", "BOGOR",
  "KARAWANG", "TASIKMALAYA", "TASIKMALAYA", "BEKASI", "BEKASI", "CIREBON", "BEKASI", "BOGOR", "MAJALENGKA", "BEKASI",
  "BEKASI", "GARUT", "CIAMIS", "MAJALENGKA", "SUMEDANG", "PURWAKARTA", "BEKASI", "BOGOR", "BEKASI", "SUKABUMI",
  "SUKABUMI", "CIANJUR", "BEKASI", "BEKASI", "DEPOK", "BOGOR", "INDRAMAYU", "DEPOK", "CIREBON", "BOGOR",
  "CIREBON", "DEPOK", "DEPOK", "KARAWANG", "BOGOR", "BEKASI", "BEKASI", "DEPOK", "BOGOR", "PURWAKARTA",
  "BEKASI", "DEPOK", "CIANJUR", "GARUT", "BOGOR", "GARUT", "BEKASI", "BANDUNG", "BEKASI", "BEKASI",
  "KUNINGAN", "BANDUNG", "BEKASI", "BOGOR", "DEPOK", "TASIKMALAYA", "BANDUNG", "BANDUNG", "BOGOR", "SUMEDANG",
  "CIREBON", "BEKASI", "BANDUNG", "TASIKMALAYA", "CIANJUR", "BEKASI", "BANDUNG", "KUNINGAN", "KARAWANG", "KARAWANG",
  "BOGOR", "BANDUNG", "BANDUNG", "SUMEDANG", "SUBANG", "SUKABUMI", "KARAWANG", "BANDUNG", "CIREBON", "KUNINGAN",
  "KARAWANG", "BANDUNG", "BANDUNG", "PURWAKARTA", "BEKASI", "CIANJUR", "SUKABUMI", "SUBANG", "KARAWANG", "PURWAKARTA",
  "BEKASI", "BEKASI", "KUNINGAN", "BANDUNG", "BOGOR", "BEKASI", "BOGOR", "BOGOR", "BANDUNG", "CIAMIS",
  "DEPOK", "CIANJUR", "BANDUNG", "SUKABUMI", "DEPOK", "INDRAMAYU", "INDRAMAYU", "INDRAMAYU", "DEPOK", "CIANJUR",
  "SUKABUMI", "TASIKMALAYA", "CIAMIS", "DEPOK", "MAJALENGKA", "SUBANG", "BANDUNG", "SUMEDANG", "BANDUNG", "BANDUNG"
];

// Generate dealer list mapping
const DEALERS = {};
DEALER_CODES.forEach((code, idx) => {
  const area = DEALER_AREAS[idx] ? ` - ${DEALER_AREAS[idx]}` : '';
  DEALERS[code] = {
    code: code,
    name: `${DEALER_NAMES[idx]}${area}`
  };
});

const DATA_DIR = path.join(__dirname, 'data');
const DATA_FILE = path.join(DATA_DIR, 'submissions.json');

// Ensure data folder and file exist
if (!fs.existsSync(DATA_DIR)) {
  fs.mkdirSync(DATA_DIR, { recursive: true });
}
if (!fs.existsSync(DATA_FILE)) {
  fs.writeFileSync(DATA_FILE, JSON.stringify({}, null, 2), 'utf8');
}

// Read database
function readDB() {
  try {
    const data = fs.readFileSync(DATA_FILE, 'utf8');
    return JSON.parse(data);
  } catch (error) {
    console.error('Error reading database file:', error);
    return {};
  }
}

// Write database
function writeDB(data) {
  try {
    fs.writeFileSync(DATA_FILE, JSON.stringify(data, null, 2), 'utf8');
    return true;
  } catch (error) {
    console.error('Error writing database file:', error);
    return false;
  }
}

module.exports = {
  DEALER_CODES,
  DEALERS,

  // Get all submissions
  getAllSubmissions() {
    return readDB();
  },

  // Get submission by dealer code
  getSubmission(code) {
    const db = readDB();
    return db[code] || null;
  },

  // Save or update submission
  saveSubmission(code, data) {
    const db = readDB();
    db[code] = {
      ...db[code],
      ...data,
      code: code,
      timestamp: new Date().toISOString()
    };
    return writeDB(db);
  },

  // Validate dealer code
  isValidDealer(code) {
    return DEALER_CODES.includes(code.toUpperCase());
  },

  // Get dealer details by code
  getDealerDetails(code) {
    return DEALERS[code.toUpperCase()] || null;
  }
};
